/* ***************************************************************************************************************  
   *
   * Date        Developer   Description
   * ==========  ==========  ===========
   * 23/02/2024  Tim Hurton  Initial Revision. Generate a PSQL call for each autogenerated report that needs to
   *                         to be run. 
   * 
   ***************************************************************************************************************  
*/   
-- This will need parameterisation
SELECT 'psql -d neowms -h 10.5.2.4 -p 5432 -U dblidl -c "copy (' ||
       REPLACE(select_statement,'""','\"') || ') TO STDOUT WITH CSV DELIMITER '','' HEADER" > $reports/' || filename || '.csv 2> $error_log/' || filename || '.err' AS filename
  FROM vw_constraint_reports ;